# config file version
apiVersion: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: InfluxDB
    # <string, required> datasource type. Required
    type: influxdb
    # <string> Sets a custom UID to reference this
    uid: P951FEA4DE68E13C5
    # <string> url
    url: http://127.0.0.1:8086
    # <string> database name, if used
    database: smartmeter
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
