{
 "title": "Schema Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Available Topics",
   "type": "table",
   "gridPos": { "h": 19, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SHOW TAG VALUES WITH KEY = \"topic\""
    }
   ]
  },
  {
   "title": "Available Types",
   "type": "table",
   "gridPos": { "h": 19, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "SHOW TAG VALUES WITH KEY = \"type\""
    }
   ]
  },
  {
   "title": "Available Meters",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "SHOW TAG VALUES WITH KEY = \"source\""
    }
   ]
  }
 ]
}