name: Build a Raspberry Pi OS image

on:
  push:
    branches:
      - "smartmeter-datacollector**"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-raspberrypi-image:
    runs-on: ubuntu-22.04

    name: Build a Raspberry Pi OS image
    steps:
      - uses: actions/checkout@v3
      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt-get -y install qemu-user-static

      - name: Build the Raspberry Pi OS image
        run: ./build-docker.sh

      - name: Archive the Raspberry Pi OS image
        uses: actions/upload-artifact@v3
        with:
          name: raspberrypi-os-image
          path: deploy/*.zip
